### ISSUE TITLE
Add feedback button on End slide

### ISSUE THREAD

**Issue by jdpigeon** [NeuroTechX/eeg-101#46]
Hopefully, this will allow us to see how we can improve the app, and also give people some easy way of contributing.

Could probably just open an email intent to my neurotechx account

**Comment by hubertjb** [comment]
Or it could also be a google form or just a shared doc?

Le 12 oct. 2017 15:19, "Dano Morrison" <notifications@github.com> a écrit :

Hopefully, this will allow us to see how we can improve the app, and also
give people some easy way of contributing.

Could probably just open an email intent to my neurotechx account

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NeuroTechX/eeg-101/issues/46>, or mute the thread
