### ISSUE TITLE
Question about plotting alpha/beta waves

### ISSUE THREAD

**Issue by mwiley63** [NeuroTechX/eeg-101#48]
Hello,

I've been playing with this repository and it has been very helpful with furthering my understanding of EEG data!  Thank you for the hard work and multiple implementations.

However, I am still confused on how I should go about plotting a series for each of the specific channels (alpha, beta, gamma, theta, and delta).  I.e. I'd like a graph that shows the current alpha value vs the current beta value over time.  I tried plotting data from listeners on ALPHA_ABSOLUTE and BETA_ABSOLUTE, but I do not get similar results to other muse apps (such as observing higher beta waves when breaking concentration).

Any advice on how to plot the values from these channels separately?  Or should I follow the PSD example from this repository?

Thanks,
Matt

**Comment by jdpigeon** [comment]
Hey Matt,

Stoked to hear you've been enjoying the app! Thanks a lot for filing an issue :tada: 

I'm pretty sure I get exactly what you're describing. Something like Muse Monitor's band power graph, right? 
<img src="https://user-images.githubusercontent.com/4932565/31773959-55ae51e6-b4b2-11e7-8aef-3427e77bf1ad.png" width="200"/>

I've been working on an implementation of this [Band Power Graph](https://github.com/NeuroTechX/eeg-101/issues/10) and will probably add it to the app sometime in the next month. It's pretty simple, though. Instead of using the ALPHA_ABSOLUTE and BETA_ABSOLUTE values from the SDK, I would recommend following the PSDGraph example, but use the BandPowerExtractor class to get the mean powers for each frequency band (alpha, beta, etc.).

The run method in your BandPowerDataSource runnable should look something like this:
```
while (keepRunning) {
                    numEEGPoints = eegBuffer.getPts();
                    // stepSize set so that code runs at 10hz (for Muse it's  26)
                    if (numEEGPoints >= stepSize) {
                        // Extract latest raw samples
                        latestSamples = eegBuffer.extractSingleChannelTransposed(256, channelOfInterest);

                        // Compute log-PSD for channel of interest
                        logpower = fft.computeLogPSD(latestSamples);

                        // Write new log-PSD in buffer
                        psdBuffer.update(logpower);

                        // Compute average PSD over buffer
                        smoothLogPower = psdBuffer.mean();
                        
                        // Get bands array [nbBands]
                        bands = bandExtractor.extract(smoothLogPower);

                        if (deltaSeries.size() >= PLOT_LENGTH) {
                            deltaSeries.remove(1);
                            thetaSeries.remove(1);
                            alphaSeries.remove(1);
                            betaSeries.remove(1);
                            gammaSeries.remove(1);
                        }

                        // update DataSeries for each Band
                        deltaSeries.addLast(bands[0]);
                        thetaSeries.addLast(bands[1]);
                        alphaSeries.addLast(bands[2]);
                        betaSeries.addLast(bands[3]);
                        gammaSeries.addLast(bands[4]);

                        eegBuffer.resetPts();
                    }
                }
```

**Comment by mwiley63** [comment]
@jdpigeon this is exactly what I was looking for (i.e. charting like Muse Monitor).  Thank you!

If I find any issues with implementation (which will more likely be on my end :P) I'll update here.
