### ISSUE TITLE
LibMuse Android SDK dependency

### ISSUE THREAD

**Issue by toncho11** [NeuroTechX/eeg-101#49]
Hi,

Does your project depends on the LibMuse Android SDK? If yes, then the license of the SDK states that " distribution of your application in a commercial store is not covered by the LibMuse SDK developer license". Can you elaborate a bit on this topic? Can people base a project on your code eeg-101 and then put it in the PlayStore?

**Comment by jdpigeon** [comment]
Hey there,

Sorry for taking so long to get back about this, I was waiting to get an official word back from Interaxon.

Yes, our project uses the LibMuse SDK license and yes, you're right about that statement in the license. What Interaxon would like is for every developer who is pushing an app to store to *commercialize* or make money in any way from it to get in contact with them to set-up a licensing agreement. The appropriate contact for that is [business at interaxon.ca].

For anyone who is releasing a free and open source app this isn't necessary.  However, they do prefer developers download the SDK through their official website, which is why I've recently removed it from this repo.

Cheers
