### ISSUE TITLE
App crashes when bt is enabled

### ISSUE THREAD

**Issue by vasyl91** [NeuroTechX/eeg-101#60]
Clean app installed via `react-native run-android` as in setup instructions crashes after clicking "Ok, it's on" on "Step 1" slide. It happens when bluetooth is on. While disabled, crashes on next slide when app propmpts to on bt. App from Play Store works flawlessly.

**Comment by jdpigeon** [comment]
I believe this is due to the not being able to find the LibMuse SDK when attempting to connect to the Muse. Download the LibMuse SDK from developers,choosemuse.com and make sure you place libmuse_android.so in <clonedRepoName>/EEG101/android/app/src/main/jniLib/armeabi-v7a/ and libmuse_android.jar in <clonedRepoName/EEG101/android/app/libs/.

If that doesn't work, keep me posted

**Comment by vasyl91** [comment]
Dano figured it out via email. The problem occured due to Libmuse. I copied only libmuse_android.jar because libmuse_android.so is already where instructions point. That was the mistake. I should have copied both of them. Now it works fine! Thanks for help.
