### ISSUE TITLE
Connect to Muse2 Model: MU-03 crashes the app

### ISSUE THREAD

**Issue by sebastus** [NeuroTechX/eeg-101#67]
Hi all - we bought the Muse2 from Muse and they shipped us a model MU-03 device. It appears to have some problems with older software. Attempting to connect to the device from this software on an Android device crashes the app. Suggestions?

**Comment by jdpigeon** [comment]
Not surprised this is happening, but thanks for reporting!

There's a lot of places where things could go wrong with the new headband and I'd probably need to look at crash logs in order to figure out where to update the app.

I'll take a look at my google developer console and see if your Muse2 crashes show up.

**Comment by sebastus** [comment]
Sounds good. FYI - the app detects the device, displays its name, then crashes.

**Comment by jdpigeon** [comment]
So, i've just heard from the Muse developers that their open source LibMuse SDK doesn't support Muse 2. However, wait until this weekend and we might have a solution for EEG 101...

**Comment by sebastus** [comment]
10-4. Thanks!
